name: CI

env:
  CI: true

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      if: github.ref == 'refs/heads/master'
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build
