name: CI

env:
  CI: true

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test
